# -----------------------------------------------------------------------------
# Kanagawa Paper Ink
# Upstream: https://github.com/thesimonho/kanagawa-paper.nvim/master/extras/wezterm/kanagawa-paper-ink.toml
# URL: https://wezterm.org/config/appearance.html
# -----------------------------------------------------------------------------

[colors]
foreground = "#DCD7BA"
background = "#1F1F28"
cursor_bg = "#c4b28a"
cursor_border = "#c4b28a"
cursor_fg = "#1F1F28"
selection_bg = "#766b90"
selection_fg = "#393836"
split = "#8992a7"
compose_cursor = "#8ea49e"
scrollbar_thumb = "#363646"

ansi = [
  "#393836",
  "#c4746e",
  "#699469",
  "#c4b28a",
  "#435965",
  "#a292a3",
  "#8ea49e",
  "#C8C093",
]
brights = [
  "#aca9a4",
  "#cc928e",
  "#72a072",
  "#d4c196",
  "#698a9b",
  "#b4a7b5",
  "#96ada7",
  "#d5cd9d",
]

[colors.indexed]
16 = "#b6927b"
17 = "#c4746e"

[colors.tab_bar]
background = "#2A2A37"
inactive_tab_edge = "#658594"

[colors.tab_bar.active_tab]
fg_color = "#c4b28a"
bg_color = "#1F1F28"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#9e9b93"
bg_color = "#2A2A37"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#a292a3"
bg_color = "#1F1F28"

[colors.tab_bar.new_tab]
fg_color = "#9e9b93"
bg_color = "#2A2A37"

[colors.tab_bar.new_tab_hover]
fg_color = "#a292a3"
bg_color = "#1F1F28"
intensity = "Bold"

[metadata]
name = "kanagawa-paper-ink"
author = "Simon Ho"
origin_url = "https://github.com/thesimonho/kanagawa-paper.nvim/master/extras/wezterm/kanagawa-paper-ink.toml"
