# -----------------------------------------------------------------------------
# Kanagawa Paper Canvas
# Upstream: https://github.com/thesimonho/kanagawa-paper.nvim/master/extras/alacritty/kanagawa-paper-canvas.toml
# URL: https://github.com/alacritty/alacritty
# -----------------------------------------------------------------------------

[colors.primary]
background = '#e1e1de'
foreground = '#54546b'

[colors.cursor]
cursor = '#618bb6'
text = '#e1e1de'

[colors.selection]
background = '#c4cbdc'
foreground = '#858479'

[colors.normal]
black = '#3e3e5a'
red = '#ba4e5a'
green = '#57786c'
yellow = '#a67337'
blue = '#719ac2'
magenta = '#a85b76'
cyan = '#526c79'
white = '#858479'

[colors.bright]
black = '#4e4e6f'
red = '#cf5865'
green = '#618679'
yellow = '#b67e3d'
blue = '#86aed7'
magenta = '#ba6683'
cyan = '#5d7a89'
white = '#919084'

[[colors.indexed_colors]]
index = 16
color = '#b8805e'

[[colors.indexed_colors]]
index = 17
color = '#ba4e5a'
